import type { HelpArticle, HelpCategory } from "./types";
export const helpCategories: HelpCategory[] = [
  { slug: "primeiros-passos", title: "Primeiros passos", description: "Configure o essencial e publique sua agenda.", icon: "book-open" },
  { slug: "agenda", title: "Agenda", description: "Crie compromissos, organize horários e bloqueios.", icon: "calendar" },
  { slug: "profissionais", title: "Profissionais", description: "Cadastre sua equipe e organize a disponibilidade.", icon: "users" },
  { slug: "servicos", title: "Serviços", description: "Monte seu catálogo com duração, valores e imagens.", icon: "briefcase" },
  { slug: "pagina-publica", title: "Página pública e links", description: "Divulgue sua agenda e facilite o agendamento.", icon: "share" },
  { slug: "clientes-aplicativo", title: "Clientes e aplicativo", description: "Entenda o Customer App, o PWA e os compromissos.", icon: "smartphone" },
  { slug: "notificacoes", title: "Lembretes e notificações", description: "Configure os canais e as antecedências.", icon: "bell" },
  { slug: "lista-espera-retorno", title: "Lista de espera e retorno", description: "Organize interessados e lembretes de retorno.", icon: "clock" },
  { slug: "whatsapp", title: "WhatsApp", description: "Conheça a automação adicional e seus requisitos.", icon: "message" },
  { slug: "plano-cobranca", title: "Plano e cobrança", description: "Veja trial, plano, adicionais e pagamentos.", icon: "credit-card" },
  { slug: "solucao-problemas", title: "Solução de problemas", description: "Encontre caminhos para as dúvidas mais comuns.", icon: "wrench" },
  { slug: "faq", title: "FAQ", description: "Respostas rápidas para perguntas frequentes.", icon: "help" },
];
const article = (categorySlug: HelpArticle["categorySlug"], slug: string, title: string, description: string, tags: string[], body: HelpArticle["body"], relatedSlugs: string[] = [], videoKey?: HelpArticle["videoKey"]): HelpArticle => ({ categorySlug, slug, title, description, tags, body, relatedSlugs, videoKey, seo: { title: `${title} | Central de Ajuda Agendoro`, description }, hasVideo: Boolean(videoKey) });
const video = (videoKey: NonNullable<HelpArticle["videoKey"]>, title: string): HelpArticle["body"][number] => ({ type: "video", videoKey, title, fallbackText: "Os passos escritos continuam disponíveis mesmo sem assistir ao vídeo." });
const steps = (items: string[]): HelpArticle["body"][number] => ({ type: "steps", items });
const note = (text: string, title = "Observação"): HelpArticle["body"][number] => ({ type: "note", title, text });
export const helpArticles: HelpArticle[] = [
  article("primeiros-passos", "conhecendo-o-agendoro", "Conhecendo o Agendoro", "Veja como o Agendoro reúne agenda, equipe, serviços, clientes e agendamentos.", ["começar", "agendoro", "visão geral"], [{ type: "paragraph", text: "O Agendoro ajuda pequenos negócios a organizar horários, profissionais, serviços, clientes e agendamentos online." }, steps(["Configure o perfil público da empresa.", "Defina horários e cadastre profissionais.", "Crie os serviços.", "Faça um teste e compartilhe seu link."])], ["configurar-empresa", "configurar-horarios", "publicar-agenda"]),
  article("primeiros-passos", "configurar-empresa", "Configurando sua empresa", "Atualize nome, endereço, logo e imagem de capa da página pública.", ["empresa", "perfil público", "logo", "capa"], [{ type: "heading", level: 2, text: "Como fazer" }, steps(["Abra Configurações.", "Preencha o nome e, se quiser, o endereço.", "Adicione ou remova logo e capa.", "Clique em Salvar perfil."]), video("company-data", "Veja como configurar os dados da empresa"), note("Essas informações aparecem para quem acessa sua agenda pública.")], ["configurar-horarios", "personalizar-pagina"], "company-data"),
  article("primeiros-passos", "configurar-horarios", "Configurando horários", "Defina os dias e horários em que seu negócio atende.", ["horários", "funcionamento", "disponibilidade"], [steps(["Abra Configurações e localize Horários de funcionamento.", "Escolha os dias de atendimento.", "Informe abertura e encerramento.", "Salve as alterações."]), video("business-hours", "Veja como configurar os horários"), note("Os horários do negócio são combinados com a disponibilidade de cada profissional e os bloqueios.")], ["disponibilidade-profissional", "bloquear-horario"], "business-hours"),
  article("primeiros-passos", "primeiro-profissional", "Cadastrando seu primeiro profissional", "Adicione quem atende e defina se terá acesso ao sistema.", ["profissional", "equipe", "acesso"], [steps(["Abra Profissionais.", "Clique em adicionar profissional.", "Informe o nome e dados públicos.", "Escolha serviços e acesso quando necessário.", "Salve."]), video("first-professional", "Veja como cadastrar o primeiro profissional")], ["disponibilidade-profissional", "limite-profissionais"], "first-professional"),
  article("primeiros-passos", "primeiro-servico", "Cadastrando seu primeiro serviço", "Crie um serviço com duração, valor, descrição e imagem.", ["serviço", "catálogo", "duração", "valor"], [steps(["Abra Serviços.", "Clique em adicionar serviço.", "Informe nome, descrição, duração e valor.", "Adicione uma imagem se quiser.", "Associe os profissionais e salve."]), video("first-service", "Veja como cadastrar o primeiro serviço"), note("Um serviço inativo ou sem profissional associado não aparece como opção pública.")], ["associar-servico-profissional", "publicar-agenda"], "first-service"),
  article("primeiros-passos", "agendamento-de-teste", "Fazendo um agendamento de teste", "Confira o fluxo antes de enviar seu link aos clientes.", ["teste", "agendamento"], [steps(["Abra a ação de agendamento de teste no Dashboard.", "Escolha serviço, profissional, data e horário.", "Informe dados de teste e confirme.", "Confira o compromisso na agenda."]), video("test-booking", "Veja como fazer um agendamento de teste")], ["visao-da-agenda", "publicar-agenda"], "test-booking"),
  article("primeiros-passos", "publicar-agenda", "Publicando e compartilhando sua agenda", "Use o link público do estabelecimento para receber agendamentos.", ["link", "publicar", "compartilhar", "agenda pública"], [steps(["Abra Configurações e localize o link público.", "Confira a página pública.", "Copie o link ou use o compartilhamento do dispositivo.", "Envie ou publique o link."]), video("publish", "Veja como publicar o link"), note("O QR Code não faz parte do Agendoro neste momento. Use o link público.", "Importante")], ["personalizar-pagina", "horario-nao-aparece"], "publish"),
  article("agenda", "visao-da-agenda", "Visão da agenda", "Consulte compromissos, filtros e detalhes do dia.", ["dashboard", "agenda", "compromissos"], [{ type: "paragraph", text: "O Dashboard concentra os próximos compromissos e permite navegar por datas. Meu Dia oferece uma visão focada para a rotina do profissional." }, steps(["Navegue para a data.", "Filtre quando necessário.", "Abra detalhes.", "Confirme, cancele ou reagende conforme o fluxo disponível."])], ["criar-agendamento", "editar-agendamento", "cancelar-agendamento"]),
  article("agenda", "criar-agendamento", "Criar um agendamento", "Marque um compromisso diretamente pela agenda do negócio.", ["criar", "agendar", "cliente", "horário"], [steps(["Abra novo agendamento no Dashboard.", "Escolha serviço, profissional e horário.", "Informe o cliente e confirme.", "Confira o compromisso."]), note("A disponibilidade é confirmada pelo sistema no momento da gravação. Se o horário estiver ocupado, escolha outro.")], ["visao-da-agenda", "horario-nao-aparece"]),
  article("agenda", "editar-agendamento", "Editar ou reagendar um agendamento", "Atualize os dados permitidos ou peça um novo horário.", ["editar", "reagendar", "alterar"], [{ type: "paragraph", text: "Abra o compromisso na agenda e use a ação disponível. O novo horário precisa continuar disponível para o profissional." }, note("Pelo link público, a solicitação de reagendamento pode gerar contato via WhatsApp quando esse canal estiver configurado.")], ["visao-da-agenda", "cancelar-agendamento"]),
  article("agenda", "cancelar-agendamento", "Cancelar um agendamento", "Cancele um compromisso pela agenda ou pelo link de gerenciamento.", ["cancelar", "agendamento"], [steps(["Abra o compromisso.", "Escolha cancelar.", "Revise a confirmação e informe o motivo quando solicitado.", "Confira o status atualizado."]), note("O cliente pode cancelar pelo link de gerenciamento enquanto ele estiver válido.")], ["editar-agendamento", "horario-nao-aparece"]),
  article("agenda", "bloquear-horario", "Bloquear horários e dias", "Impeça novos agendamentos em um período ou dia específico.", ["bloqueio", "feriado", "indisponibilidade"], [steps(["Abra Bloqueios.", "Escolha o período ou dia.", "Defina o escopo do negócio ou profissional.", "Salve e confira a página pública."]), note("Use a disponibilidade do profissional para regras recorrentes.")], ["disponibilidade-profissional", "horario-nao-aparece"]),
  article("profissionais", "disponibilidade-profissional", "Configurar horários do profissional", "Defina quando cada profissional pode receber agendamentos.", ["profissional", "disponibilidade", "horários"], [steps(["Abra Disponibilidade.", "Selecione o profissional.", "Adicione, edite ou remova regras.", "Salve."]), note("O sistema combina essa configuração com o horário do negócio, serviços, compromissos e bloqueios.")], ["bloquear-horario", "horario-nao-aparece"]),
  article("profissionais", "limite-profissionais", "Limite e profissionais adicionais", "Entenda o limite incluído no plano.", ["limite", "adicional", "plano", "profissional"], [{ type: "paragraph", text: "O plano Agendoro inclui até 3 profissionais. Profissionais adicionais são cobrados separadamente." }, steps(["Abra Faturamento.", "Confira a quantidade de profissionais ativos.", "Consulte a opção adicional antes de contratar."]), note("O catálogo atual indica R$ 15 por profissional adicional ao mês. Confirme a tela de Faturamento.", "Valor vigente")], ["primeiro-profissional", "entenda-seu-plano"]),
  article("servicos", "associar-servico-profissional", "Associar serviços a profissionais", "Escolha quais profissionais oferecem cada serviço.", ["serviço", "profissional", "associação"], [steps(["Abra Serviços e escolha um serviço.", "Acesse o gerenciamento de profissionais.", "Associe ou desassocie profissionais.", "Confira a página pública."]), note("Serviços inativos não ficam disponíveis para novas associações públicas.")], ["primeiro-servico", "horario-nao-aparece"]),
  article("pagina-publica", "personalizar-pagina", "Personalizar a página pública", "Ajuste a identidade que os clientes veem antes de agendar.", ["personalização", "logo", "capa", "página pública"], [steps(["Abra Configurações.", "Atualize nome, logo, capa e endereço.", "Salve.", "Abra o catálogo público para conferir."]), video("appearance", "Veja como personalizar o perfil público")], ["publicar-agenda", "configurar-empresa"], "appearance"),
  article("clientes-aplicativo", "meus-compromissos", "Meus Compromissos e o aplicativo do cliente", "Saiba o que o cliente consulta depois de agendar.", ["cliente", "app", "PWA", "compromissos"], [{ type: "paragraph", text: "Depois de um agendamento público, o cliente pode acessar o Customer App pelo link do estabelecimento e consultar próximos compromissos e detalhes." }, steps(["Abra o link no celular.", "Use a sessão criada após o agendamento quando disponível.", "Consulte o próximo compromisso ou abra um item da lista."])], ["instalar-aplicativo", "push-notifications"]),
  article("clientes-aplicativo", "instalar-aplicativo", "Instalar o aplicativo no celular", "Use a instalação oferecida pelo navegador quando ela estiver disponível.", ["instalar", "PWA", "celular", "aplicativo"], [steps(["Abra o link do estabelecimento em navegador compatível.", "Procure o cartão ou opção de instalar.", "Confirme a instalação.", "Abra o ícone instalado."]), note("A opção depende do navegador, dispositivo e condições de instalação. Se não aparecer, use o link no navegador.", "Problema de instalação")], ["meus-compromissos", "push-notifications"]),
  article("notificacoes", "push-notifications", "Como funcionam as notificações push", "Entenda as permissões necessárias para receber lembretes.", ["push", "notificação", "permissão", "lembrete"], [{ type: "paragraph", text: "Push depende do navegador/dispositivo e da permissão dada pelo cliente." }, steps(["Abra o aplicativo no celular.", "Permita notificações quando solicitado.", "Mantenha a permissão ativa.", "Se bloqueou, reative nas configurações do navegador ou dispositivo."]), note("Build e computador não garantem entrega: o dispositivo precisa suportar push e ter permissão ativa.")], ["configurar-lembretes", "instalar-aplicativo"]),
  article("notificacoes", "configurar-lembretes", "Configurar lembretes de compromisso", "Escolha antecedência e canais para os lembretes.", ["lembrete", "e-mail", "push", "whatsapp"], [steps(["Abra Configurações e localize Lembretes.", "Ative os lembretes.", "Escolha antecedências.", "Selecione canais configurados.", "Salve."]), video("notifications", "Veja como configurar notificações"), note("Push, e-mail e WhatsApp têm requisitos diferentes.")], ["push-notifications", "whatsapp-adicional"], "notifications"),
  article("lista-espera-retorno", "lista-de-espera", "Como funciona a lista de espera", "Registre interessados quando não houver horário adequado.", ["lista de espera", "fila", "vaga"], [steps(["Abra Lista de Espera.", "Informe nome, telefone e serviço.", "Adicione profissional, período ou data quando fizer sentido.", "Acompanhe e remova entradas."]), note("Em alguns conflitos públicos, o sistema oferece um link pré-preenchido. A entrada não confirma agendamento.")], ["lembrete-retorno", "horario-nao-aparece"]),
  article("lista-espera-retorno", "lembrete-retorno", "Lembrete automático de retorno", "Reative clientes sem novo agendamento.", ["retorno", "reativação", "cliente", "lembrete"], [steps(["Abra Configurações e localize Lembrete de retorno.", "Ative a automação.", "Defina dias e intervalo mínimo.", "Escolha canais e template quando necessário.", "Salve e teste quando disponível."]), note("WhatsApp exige template configurado; canais dependem de configuração externa.")], ["lista-de-espera", "configurar-lembretes"]),
  article("whatsapp", "whatsapp-adicional", "O que é a Automação WhatsApp", "Conheça o adicional e seus requisitos.", ["whatsapp", "meta", "automação", "adicional"], [{ type: "paragraph", text: "A Automação WhatsApp é um adicional para mensagens de fluxos configurados, como lembretes e retorno. Não é requisito para usar agenda, página pública ou aplicativo." }, steps(["Confira o adicional em Faturamento.", "Tenha conta e número compatíveis com a Meta.", "Conclua a ativação na área de WhatsApp.", "Sincronize e teste conforme a tela."]), note("O catálogo atual indica R$ 100 por mês e R$ 297 para implantação WhatsApp. Podem existir custos e regras externos da Meta.", "Custos e limitações")], ["configurar-lembretes", "entenda-seu-plano"]),
  article("plano-cobranca", "entenda-seu-plano", "Entenda seu plano", "Veja o que está incluído no Agendoro e como funciona o teste.", ["plano", "trial", "cobrança", "preço"], [{ type: "paragraph", text: "O catálogo vigente indica R$ 97 ao mês ou R$ 970 ao ano e inclui até 3 profissionais. A tela de Faturamento é a fonte para confirmar a contratação e os recursos habilitados para a conta." }, { type: "heading", level: 2, text: "Teste grátis" }, { type: "paragraph", text: "O teste dura 14 dias e não exige cartão. A assinatura é iniciada pelo cliente na tela de Faturamento." }, steps(["Profissional adicional: R$ 15 por mês.", "Automação WhatsApp: R$ 100 por mês.", "Implantação assistida: R$ 197 em compra única.", "Implantação WhatsApp: R$ 297 em compra única."]), note("Não há, no catálogo/backend auditado, uma regra explícita que permita afirmar limites de serviços, clientes ou agendamentos. Confirme valores e opções na tela de Faturamento antes de contratar.", "Confirme antes de contratar")], ["pagamento-e-cobranca", "limite-profissionais", "whatsapp-adicional"]),
  article("plano-cobranca", "pagamento-e-cobranca", "Pagamento, falha de cobrança e cancelamento", "Acompanhe o status financeiro do Agendoro.", ["pagamento", "cobrança", "cancelar", "pendente"], [steps(["Abra Faturamento.", "Confira status, plano e pagamentos.", "Regularize um pagamento pendente pela tela indicada.", "Use a ação de cancelamento disponível na assinatura."]), note("A confirmação pode levar alguns instantes. Guarde o comprovante se o status não atualizar.", "Pagamento pendente")], ["entenda-seu-plano", "problema-login"]),
  article("solucao-problemas", "horario-nao-aparece", "O horário não aparece para o cliente", "Confira o que controla a disponibilidade pública.", ["horário", "disponibilidade", "cliente", "agenda"], [{ type: "troubleshooting", title: "Verifique nesta ordem", items: ["Serviço ativo e associado ao profissional.", "Horário de funcionamento do negócio.", "Disponibilidade do profissional.", "Bloqueios, feriados ou outro compromisso.", "Data e fuso horário mostrados na página pública."] }, { type: "link", label: "Configurar disponibilidade do profissional", href: "/ajuda/profissionais/disponibilidade-profissional" }], ["disponibilidade-profissional", "associar-servico-profissional", "bloquear-horario"]),
  article("solucao-problemas", "servico-nao-aparece", "O serviço não aparece", "Confira as configurações que controlam a publicação.", ["serviço", "catálogo", "público"], [{ type: "troubleshooting", title: "Confira", items: ["O serviço está ativo?", "Existe profissional associado?", "O profissional está ativo?", "Você abriu a página pública correta?"] }], ["primeiro-servico", "associar-servico-profissional", "publicar-agenda"]),
  article("solucao-problemas", "notificacao-nao-chegou", "O cliente não recebeu uma notificação", "Veja o que conferir antes de tentar novamente.", ["notificação", "push", "e-mail", "whatsapp"], [{ type: "troubleshooting", title: "Confira", items: ["Canal ativado nos lembretes.", "E-mail ou telefone corretos.", "Permissão de push ativa.", "Conta e template de WhatsApp configurados.", "Horário do lembrete ainda não passou."] }, note("A Central não confirma a entrega de um canal externo apenas pela configuração.")], ["configurar-lembretes", "push-notifications", "whatsapp-adicional"]),
  article("solucao-problemas", "problema-login", "Problema de login", "Recupere o acesso quando não conseguir entrar.", ["login", "senha", "acesso"], [steps(["Confira o e-mail.", "Use Esqueci minha senha.", "Abra o link recebido e crie nova senha.", "Verifique spam se o e-mail não chegar."])], ["pagamento-e-cobranca"]),
  article("faq", "faq-agendoro", "Perguntas frequentes", "Respostas rápidas para começar e operar o Agendoro.", ["faq", "dúvidas", "perguntas"], [{ type: "heading", level: 2, text: "Preciso de cartão para testar?" }, { type: "paragraph", text: "Não. O teste atual dura 14 dias e não exige cartão." }, { type: "heading", level: 2, text: "O WhatsApp é obrigatório?" }, { type: "paragraph", text: "Não. A Automação WhatsApp é um adicional." }, { type: "heading", level: 2, text: "Existe Google Calendar?" }, { type: "paragraph", text: "Não encontramos essa integração disponível no Agendoro atual." }, { type: "heading", level: 2, text: "Existe QR Code?" }, { type: "paragraph", text: "Não. Use o link público para divulgar sua agenda." }], ["entenda-seu-plano", "whatsapp-adicional", "publicar-agenda"]),
];
export const helpArticleBySlug = new Map(helpArticles.map((item) => [item.slug, item]));
export const helpCategoryBySlug = new Map(helpCategories.map((item) => [item.slug, item]));
export function articleUrl(article: Pick<HelpArticle, "categorySlug" | "slug">): string { return `/ajuda/${article.categorySlug}/${article.slug}`; }
export function categoryUrl(slug: string): string { return `/ajuda/${slug}`; }
