services:
  frontend:
    image: ghcr.io/mdauri/agendoro-frontend:latest
    container_name: agendoro-frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.agendoro-frontend.rule=Host(`agenda.dauri.com.br`)"
      - "traefik.http.routers.agendoro-frontend.entrypoints=websecure"
      - "traefik.http.routers.agendoro-frontend.tls=true"
      - "traefik.http.routers.agendoro-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.agendoro-frontend.loadbalancer.server.port=80"

networks:
  web:
    external: true
